import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import {dirname,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
import {parseText,serialize,noteName,noteNumber,definitionNotes} from './dist/core.js';
const catalog=JSON.parse(await readFile('dist/samples/index.json','utf8')),profiles=JSON.parse(await readFile('dist/instruments.json','utf8')),allowed=definitionNotes(profiles[0]);
// 依存関係は追加しない。既存のPlaywright、またはCodex同梱ランタイムで実行する。
let automation;try{automation=await import('playwright');}catch{automation=await import(pathToFileURL(resolve(dirname(process.execPath),'../node_modules/playwright/index.mjs')));}
const browser=await automation.chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})});
const errors=[],requests=[];
await mkdir('.sites-runtime',{recursive:true});
try{
  // 曲の各版をまとめ、表示言語や音色が変わっても音域で選べることを確認する。
  const versionsPage=await browser.newPage({viewport:{width:1280,height:900}}),versionErrors=[];
  versionsPage.on('pageerror',error=>versionErrors.push(error.message));
  const base=catalog.samples.find(item=>item.id==='pachelbel-canon-musicbox-30'),bodies=new Map();
  const sample=(profile,midi,changes={})=>{
    const id='check-'+profile+Object.keys(changes).join('-'),metadata={...base.metadata,arranged_for:profile,...changes};
    bodies.set(id+'.txt',serialize([{step:0,midi}],2,200,metadata));return {id,file:id+'.txt',metadata,usedNotes:[midi],length:2,stepMs:200};
  };
  const versions=[sample('musicbox30',72),sample('piano88',21),sample('piano61',36),sample('xylophone32',77),sample('piano88',72,{title:'Other',title_ja:'別の曲',title_en:'Other',reading_ja:'べつのきょく'}),sample('musicbox30',72,{composer:'Other composer',composer_ja:'別の作曲者',composer_en:'Other composer'})];
  await versionsPage.route('**/samples/index.json',route=>route.fulfill({json:{revision:'check',samples:versions}}));
  await versionsPage.route('**/samples/*.txt*',route=>route.fulfill({contentType:'text/plain;charset=utf-8',body:bodies.get(decodeURIComponent(new URL(route.request().url()).pathname.split('/').at(-1)))}));
  await versionsPage.goto(process.argv[2]??'http://127.0.0.1:4173');await versionsPage.waitForSelector('#instrument option',{state:'attached'});
  const openVersions=async()=>{await versionsPage.locator('#templateButton').click();await versionsPage.waitForFunction(()=>{const menu=document.querySelector('#templateMenu'),rect=menu.getBoundingClientRect();return menu.matches(':popover-open')&&document.querySelector('#templateButton').getAttribute('aria-expanded')==='true'&&Math.abs(rect.top-document.querySelector('#templateButton').getBoundingClientRect().bottom-5)<1&&Math.abs(parseFloat(menu.style.maxHeight)-(innerHeight-rect.top-8))<1&&rect.left>=0&&rect.right<=innerWidth&&rect.top>=0&&rect.bottom<=innerHeight;});};
  assert.equal(await versionsPage.locator('.template-song').count(),3,'同じ原題・作曲者の版をまとめ、同名の別作曲者は分ける');
  assert.equal(await versionsPage.locator('[data-sample="check-piano88title-title_ja-title_en-reading_ja"]').count(),2,'別の音域向けでも使用音が対応すれば選べる');
  await openVersions();const canonRow=versionsPage.locator('.template-song').filter({has:versionsPage.locator('.template-versions [data-sample="check-musicbox30"]')});
  for(const query of ['かのん','ｶﾉﾝ','ＣＡＮＯＮ']){await versionsPage.locator('#templateSearch').fill(query);assert(await canonRow.isVisible(),'表記差を吸収して曲名を検索する');}
  await versionsPage.locator('#templateSearch').fill('___該当なし___');assert(await versionsPage.locator('#templateEmpty').isVisible());assert.equal(await versionsPage.locator('.template-song:visible').count(),0);
  await versionsPage.locator('#templateSearch').fill('');assert.equal(await versionsPage.locator('.template-song:visible').count(),3);await canonRow.locator('.template-title').focus();
  assert.equal(await canonRow.locator('.template-title').getAttribute('data-sample'),'check-musicbox30');assert.equal(await canonRow.locator('.recommended').textContent(),'musicbox30');
  await versionsPage.keyboard.press('Escape');await versionsPage.waitForFunction(()=>document.querySelector('#templateButton').getAttribute('aria-expanded')==='false');assert.equal(await versionsPage.evaluate(()=>document.activeElement.id),'templateButton');
  await versionsPage.selectOption('#instrument','piano-88');await openVersions();assert.equal(await canonRow.locator('.recommended').textContent(),'piano88');
  await canonRow.locator('.template-title').click();await versionsPage.waitForFunction(()=>document.querySelector('#scoreTitle').value==='カノン');assert.equal(parseText(await versionsPage.locator('#txtPreview').inputValue()).notes[0].midi,21,'曲名から現在の音域向けを選ぶ');
  await openVersions();await canonRow.locator('.template-versions [data-sample="check-musicbox30"]').click();await versionsPage.waitForFunction(()=>document.querySelector('#txtPreview').value.includes('\nC5\n'));assert.equal(await versionsPage.locator('#instrument').inputValue(),'piano-88','指定版の読み込みで楽器・音色を変えない');
  await versionsPage.keyboard.press('Control+z');assert.equal(parseText(await versionsPage.locator('#txtPreview').inputValue()).notes[0].midi,21,'版の変更も取り消せる');
  await versionsPage.selectOption('#instrument','marimba-61');await openVersions();assert.equal(await canonRow.locator('.recommended').textContent(),'piano61');assert.equal(await canonRow.locator('.template-versions [data-sample="check-piano88"]').count(),0,'非対応音を持つ版を隠す');
  await canonRow.locator('.template-title').click();await versionsPage.waitForFunction(()=>document.querySelector('#txtPreview').value.includes('\nC2\n'));
  await versionsPage.selectOption('#language','en');await versionsPage.waitForFunction(()=>document.documentElement.lang==='en');assert.equal(await versionsPage.locator('.template-song').count(),3,'翻訳後も同じ曲をまとめる');
  await versionsPage.locator('#templateButton').press('ArrowDown');await versionsPage.waitForFunction(()=>document.querySelector('#templateMenu').matches(':popover-open')&&document.activeElement.className==='template-title');assert.equal(await versionsPage.evaluate(()=>document.activeElement.className),'template-title');
  await canonRow.locator('.template-title').focus();await versionsPage.keyboard.press('Tab');assert.equal(await versionsPage.evaluate(()=>document.activeElement.textContent),'piano61');await versionsPage.keyboard.press('Enter');await versionsPage.waitForFunction(()=>!document.querySelector('#templateMenu').matches(':popover-open'));assert.equal(await versionsPage.locator('#scoreTitle').inputValue(),'Canon');
  await versionsPage.setViewportSize({width:390,height:844});await openVersions();assert(await versionsPage.locator('#templateMenu').evaluate(element=>{const rect=element.getBoundingClientRect();return rect.left>=0&&rect.right<=innerWidth&&rect.top>=0&&rect.bottom<=innerHeight;}),'狭い画面でも一覧全体を画面内に収める');
  await versionsPage.screenshot({path:'.sites-runtime/template-versions-mobile.png'});await versionsPage.locator('#templateButton').click();assert(!(await versionsPage.locator('#templateMenu').evaluate(element=>element.matches(':popover-open'))));
  await versionsPage.selectOption('#instrument','xylophone-32');await openVersions();assert.equal(await versionsPage.locator('.template-song').count(),1);assert.equal(await versionsPage.locator('.template-song .recommended').textContent(),'xylophone32');
  await versionsPage.keyboard.press('Escape');await versionsPage.unroute('**/samples/index.json');await versionsPage.route('**/samples/index.json',route=>route.fulfill({json:{revision:'fallback',samples:versions.filter(item=>item.id!=='check-piano88')}}));await versionsPage.reload();await versionsPage.waitForSelector('#instrument option',{state:'attached'});await versionsPage.selectOption('#instrument','piano-88');assert.equal(await canonRow.locator('.recommended').textContent(),'piano61','同じ音域の版がなければ演奏可能な広い音域の版を選ぶ');
  assert(!versionErrors.length,versionErrors.join('\n'));await versionsPage.close();
  const page=await browser.newPage({viewport:{width:1280,height:900}});page.setDefaultTimeout(15000);
  page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>requests.push(request.url()));
  await page.goto(process.argv[2]??'http://127.0.0.1:4173');await page.waitForSelector('#instrument option',{state:'attached'});
  const chooseTemplate=async id=>{await page.locator('#templateButton').click();await page.locator(`.template-versions [data-sample="${id}"]`).click();};
  const transpose=async amount=>{for(let remaining=Math.abs(amount);remaining>0;){const octave=remaining>=12;await page.locator(amount>0?'#transposeUp':'#transposeDown').click({modifiers:octave?['Shift']:[]});remaining-=octave?12:1;}};
  assert.equal(await page.locator('#transposeMenu,#transpose,#applyTranspose,#transposeButton').count(),0,'移調の数値入力・適用用ポップアップを残さない');
  assert.equal(await page.locator('#soundset').count(),0,'楽器だけ選択し、音源の選択欄を設けない');
  assert.deepEqual(await page.locator('#instrument option').evaluateAll(options=>options.map(option=>option.value)),['musicbox-30','piano-88','piano-61','marimba-61','xylophone-32']);
  assert.equal(await page.locator('#status').count(),0);assert(await page.locator('#errorMessage').isHidden());assert.equal(await page.locator('#timeSelectionStats').count(),0);assert.equal(await page.locator('#copyText').textContent(),'TXTコピー');assert.equal(await page.locator('#copyText').getAttribute('title'),'StepScore形式のテキストでコピー');assert.equal(await page.locator('#roll').getAttribute('title'),'Shift＋クリック：選択、ドラッグ：選択・移動');assert.equal(await page.locator('#deleteRange').textContent(),'削除');assert.equal(await page.locator('#deleteRange').getAttribute('title'),'Delete / Backspace');assert.equal(await page.locator('#collapseRange').textContent(),'削除して詰める');assert.equal(await page.locator('#collapseRange').getAttribute('title'),'Shift + Delete / Backspace');assert(await page.locator('#collapseRange').isDisabled());
  assert.equal(await page.locator('#noteStats').textContent(),'0音 · 32ステップ');assert.deepEqual(await page.locator('.template-versions button').evaluateAll(buttons=>buttons.map(button=>button.dataset.sample).sort()),catalog.samples.filter(item=>item.usedNotes.every(note=>allowed.has(note))).map(item=>item.id).sort());
  assert(!requests.some(url=>/vendor\/midi|\.ogg(?:\?|$)|\/samples\/[^/]+\.txt/.test(url)),'初期表示でMIDIライブラリ・全音源・全曲を読み込まない');
  assert(await page.locator('#rollViewport').evaluate(element=>element.scrollHeight<=element.clientHeight),'30音の鍵盤を縦スクロールなしで展開');await page.locator('.cell[data-step="0"][data-midi="72"]').hover();const beforeWheel=await page.evaluate(()=>scrollY);await page.mouse.wheel(0,200);await page.waitForFunction(before=>scrollY>before,beforeWheel);
  await chooseTemplate('pachelbel-canon-musicbox-30');await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='カノン');
  const canon=parseText(await page.locator('#txtPreview').inputValue()),canonSource=parseText(await readFile('dist/samples/pachelbel-canon-musicbox-30.txt','utf8'));assert.equal(canon.length,canonSource.length);assert.deepEqual(canon.notes,canonSource.notes);assert.deepEqual(canon.metadata,Object.fromEntries(Object.entries(canonSource.metadata).filter(([key])=>['format','version','step_ms','title'].includes(key)||key.startsWith('title_'))),'基本名・表示名を保ち、サンプル管理用の項目を含めない');
  const preview=page.locator('#txtPreview'),canonText=await preview.inputValue();assert.equal(canonText.split('\n').length,canon.length+2,'ヘッダーと各ステップの改行を保持');assert(!canonText.includes('\r'),'プレビューの改行はLF');await page.locator('#txtPreviewPanel summary').click();assert(await preview.evaluate(element=>element.scrollWidth<=element.clientWidth),'長いヘッダーを画面内で折り返す');assert.equal(await preview.inputValue(),canonText,'表示の折り返しをデータに加えない');await page.locator('#scoreTitle').fill('取消す曲名');await page.locator('#scoreTitle').press('Escape');assert.equal(await page.locator('#scoreTitle').inputValue(),'カノン');assert.equal(await preview.inputValue(),canonText,'曲名の取消しをプレビューにも反映');await page.locator('#scoreTitle').fill('確定した曲名');assert(!Object.keys(parseText(await preview.inputValue()).metadata).some(key=>key.startsWith('title_')),'入力中のプレビューでも改名時は翻訳名を省く');await page.locator('#scoreTitle').press('Enter');assert.equal(parseText(await preview.inputValue()).metadata.title,'確定した曲名');await page.keyboard.press('Control+z');assert.equal(await preview.inputValue(),canonText,'曲名の取り消しも元のプレビューに戻す');await page.locator('#txtPreviewPanel summary').click();
  const tempo=page.locator('#bpm');assert.equal(await tempo.inputValue(),'55');assert.equal(canon.stepMs,136,'整数表示でも元の136msを保持');
  await tempo.press('ArrowUp');await tempo.press('Tab');assert.equal(await tempo.inputValue(),'56');assert.equal(parseText(await page.locator('#txtPreview').inputValue()).stepMs,134);
  await tempo.press('ArrowDown');await tempo.press('Tab');assert.equal(await tempo.inputValue(),'55');
  await tempo.fill('55.6');await tempo.press('Tab');assert.equal(await tempo.inputValue(),'56','手入力の小数も確定時に整数化');await tempo.fill('55');await tempo.press('Tab');
  await page.selectOption('#language','en');await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='Canon');assert.match(await page.locator('#noteStats').textContent(),/notes.*steps/);assert.deepEqual(parseText(await preview.inputValue()).metadata,canon.metadata,'言語切り替えでは基本名と翻訳名を保持');
  assert.equal(await page.locator('#copyText').textContent(),'Copy TXT');assert.equal(await page.locator('#copyText').getAttribute('title'),'Copy text in StepScore format');assert.equal(await page.locator('#deleteRange').textContent(),'Delete');assert.equal(await page.locator('#collapseRange').textContent(),'Delete & close gap');
  await page.locator('#scoreTitle').fill('My custom score');await page.locator('#bpm').click();await page.locator('#scoreTitle').fill('取消す別の曲名');await page.locator('#scoreTitle').press('Escape');assert.equal(parseText(await preview.inputValue()).metadata.title,'My custom score');await page.selectOption('#language','ja');await page.waitForFunction(()=>document.documentElement.lang==='ja');assert.equal(await page.locator('#scoreTitle').inputValue(),'My custom score');assert(!Object.keys(parseText(await preview.inputValue()).metadata).some(key=>key.startsWith('title_')));await page.keyboard.press('Control+z');assert.equal(await page.locator('#scoreTitle').inputValue(),'カノン','英語での改名を日本語で取り消すと日本語名へ戻す');assert.deepEqual(parseText(await preview.inputValue()).metadata,canon.metadata);await page.locator('#scoreTitle').fill('My custom score');await page.locator('#scoreTitle').press('Enter');
  await page.locator('.cell[data-step="1"][data-midi="66"]').click();assert.equal(await page.locator('.cell[data-step="1"][data-midi="66"]').getAttribute('aria-pressed'),'true');assert(await page.locator('#unsupportedPanel').isVisible());
  assert.equal(await page.locator('#exportWarning').textContent(),'非対応：1音（再生・出力から除外）');assert.equal(await page.locator('#removeUnsupported').textContent(),'非対応の音を削除');await page.context().grantPermissions(['clipboard-read','clipboard-write']);await page.locator('#copyText').click();assert.deepEqual(parseText(await page.evaluate(()=>navigator.clipboard.readText())),parseText(await page.locator('#txtPreview').inputValue()));assert(await page.locator('#errorMessage').isHidden(),'コピー完了の通知は表示しない');
  const save=async()=>{await page.locator('#save').click();const pending=page.waitForEvent('download');await page.locator('#export').click();const download=await pending,text=await readFile(await download.path(),'utf8');assert.equal(text,await preview.inputValue(),'TXT書き出しは折り返しを含まずプレビューの実データと一致');return parseText(text);};
  const instrumentText=await save();assert(!instrumentText.notes.some(note=>note.midi===66));assert.equal(instrumentText.length,canon.length);assert.equal(instrumentText.notes.length,canon.notes.length);
  await page.locator('#save').click();const midiPending=page.waitForEvent('download');await page.locator('#exportMidi').click();const midiFile=await midiPending,{Midi}=createRequire(import.meta.url)('@tonejs/midi'),exportedMidi=new Midi(await readFile(await midiFile.path()));assert.equal(exportedMidi.tracks[0].notes.length,instrumentText.notes.length);assert(!exportedMidi.tracks[0].notes.some(note=>note.midi===66));assert.deepEqual(exportedMidi.header.timeSignatures[0].timeSignature,[4,4],'MIDIはTXT出力で省いた拍子も編集中のデータから出力する');assert.equal(exportedMidi.tracks[0].controlChanges[123][0].ticks,instrumentText.length*exportedMidi.header.ppq/8);
  await page.selectOption('#instrument','piano-88');assert(await page.locator('#rollViewport').evaluate(element=>element.scrollHeight<=element.clientHeight),'88鍵でも縦スクロールなしで展開');assert(!(await page.locator('#unsupportedPanel').isVisible()));assert(parseText(await page.locator('#txtPreview').inputValue()).notes.some(note=>note.midi===66));const saved=await save();assert(saved.notes.some(note=>note.midi===66),'88鍵の音はピアノを選んで書き出す');assert.equal(saved.notes.length,instrumentText.notes.length+1);assert.equal(saved.length,instrumentText.length);assert.equal(saved.metadata.title,'My custom score');
  const pianoResponse=page.waitForResponse(response=>response.url().includes('/audio/vsco-piano/C5.ogg'));await page.locator('.key-preview[data-midi="72"]').click();assert.equal((await pianoResponse).status(),200,'ピアノを選ぶだけで録音ピアノを読み込む');assert.deepEqual(parseText(await preview.inputValue()),saved,'鍵盤の試聴で楽譜を変更しない');
  await page.selectOption('#instrument','musicbox-30');assert(await page.locator('#unsupportedPanel').isVisible());const boxResponse=page.waitForResponse(response=>response.url().includes('/audio/musicbox-30/C5.ogg'));await page.locator('.key-preview[data-midi="72"]').click();assert.equal((await boxResponse).status(),200,'楽器の切り替えで録音オルゴールに切り替わる');assert.deepEqual(parseText(await preview.inputValue()),instrumentText);await page.selectOption('#instrument','piano-88');assert.deepEqual(parseText(await preview.inputValue()),saved,'楽器・音源の切り替えで編集中の全音を保持');await page.selectOption('#instrument','musicbox-30');
  // ピアノ用に書き出した音とメタデータを実際に再取り込みする。
  await page.locator('#fileInput').setInputFiles({name:'roundtrip.txt',mimeType:'text/plain',buffer:Buffer.from(serialize(saved.notes,saved.length,saved.stepMs,saved.metadata))});await page.waitForFunction(()=>!document.querySelector('#midiPanel').hidden&&document.querySelector('#cancelImport').hidden);
  assert.equal(await page.locator('#scoreTitle').inputValue(),'My custom score');await page.selectOption('#language','en');await page.waitForFunction(()=>document.documentElement.lang==='en');assert.equal(await page.locator('#scoreTitle').inputValue(),'My custom score');
  await page.selectOption('#instrument','piano-88');await page.waitForFunction(()=>document.querySelector('#suggest').textContent.includes('Recommended'));
  await page.selectOption('#subdivision','4');await page.waitForFunction(()=>document.querySelector('.step-label[data-step="4"]')?.textContent==='2'&&document.querySelector('#cancelImport').hidden);
  const before=parseText(await page.locator('#txtPreview').inputValue());
  await page.locator('#fileInput').setInputFiles('.sites-runtime/large-import-check.mid');await page.locator('#cancelImport').click();assert.deepEqual(parseText(await page.locator('#txtPreview').inputValue()).notes,before.notes,'中止で編集中の全音を保持');
  await page.evaluate(()=>{window.checkTicks=0;window.checkGap=0;window.checkLast=performance.now();window.checkTimer=setInterval(()=>{const now=performance.now();window.checkGap=Math.max(window.checkGap,now-window.checkLast);window.checkLast=now;window.checkTicks++;},25);});
  const began=performance.now();await page.locator('#fileInput').setInputFiles('.sites-runtime/large-import-check.mid');await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='large-import-check'&&document.querySelector('#cancelImport').hidden);
  const elapsed=performance.now()-began,performanceResult=await page.evaluate(()=>{clearInterval(window.checkTimer);return {ticks:window.checkTicks,maxGap:window.checkGap,...document.querySelector('#roll').dataset};});
  const large=parseText(await page.locator('#txtPreview').inputValue());assert.equal(large.notes.length,80000);assert.equal(large.length,16000);assert(Number(performanceResult.cells)<6000,'長さに比例する全マスを作らない');assert(performanceResult.ticks>2,'Worker解析中もメインスレッドが動く');
  console.log('ブラウザ：80,000音・16,000ステップ', {elapsedMs:elapsed,...performanceResult});
  for(const width of [1280,390]){
    await page.setViewportSize({width,height:900});const positions=async()=>Promise.all(['trackSummary','suggest'].map(id=>page.locator('#'+id).boundingBox())),closed=await positions();await page.locator('#trackSummary').click();assert(await page.locator('#trackList').isVisible());assert.deepEqual(await positions(),closed,`${width}pxでもトラック一覧の開閉で操作欄を動かさない`);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'トラック一覧を開いても画面から横にはみ出さない');await page.locator('#trackSummary').click();assert.deepEqual(await positions(),closed,'一覧を閉じても操作欄を動かさない');
  }
  await page.setViewportSize({width:1280,height:900});
  await page.evaluate(()=>{const viewport=document.querySelector('#rollViewport');viewport.scrollLeft=viewport.scrollWidth;});await page.waitForSelector('.cell[data-step="15999"]',{state:'attached'});assert(await page.locator('.cell').count()<6000);
  await page.locator('#fileInput').setInputFiles({name:'broken.mid',mimeType:'audio/midi',buffer:Buffer.from('invalid')});await page.waitForFunction(()=>document.querySelector('#errorMessage').textContent!==''&&document.querySelector('#cancelImport').hidden);assert.deepEqual(parseText(await page.locator('#txtPreview').inputValue()).notes,large.notes,'失敗で現在の楽譜を保持');assert(!/[ぁ-んァ-ヶ一-龥]/.test(await page.locator('#errorMessage').textContent()),'英語エラー表示');
  await page.selectOption('#language','ja');await page.waitForFunction(()=>document.documentElement.lang==='ja');await page.locator('#reset').click();await page.selectOption('#instrument','musicbox-30');
  const cell=page.locator('.cell[data-step="0"][data-midi="72"]');await cell.scrollIntoViewIfNeeded();const start=await cell.boundingBox(),end=await page.locator('.cell[data-step="3"][data-midi="72"]').boundingBox();
  await page.mouse.move(start.x+start.width/2,start.y+start.height/2);await page.mouse.down();await page.mouse.move(end.x+end.width/2,end.y+end.height/2,{steps:12});await page.mouse.up();assert.equal(parseText(await page.locator('#txtPreview').inputValue()).notes.length,4,'押したまま連続入力');
  await page.keyboard.press('Control+z');assert.equal(parseText(await page.locator('#txtPreview').inputValue()).notes.length,0,'連続入力を1回で取り消し');
  await cell.click();await cell.click({modifiers:['Shift']});await cell.press('Shift+ArrowRight');assert.equal(parseText(await page.locator('#txtPreview').inputValue()).notes[0].step,1,'選択した音の移動');
  await page.keyboard.press('Control+z');assert.equal(parseText(await page.locator('#txtPreview').inputValue()).notes[0].step,0);
  await page.locator('#play').click();await page.waitForSelector('.step-label.playing');assert(await page.locator('#errorMessage').isHidden(),'試聴中の通知は表示しない');await page.locator('#play').click();assert(await page.locator('#errorMessage').isHidden(),'停止時の通知は表示しない');assert(requests.some(url=>url.includes('/audio/musicbox-30/C5.ogg')),'移動した録音を実際に読み込み・デコードする');assert(!errors.length,errors.join('\n'));
  // 88鍵外の音は編集データに保持し、出力は対応音だけ。独自の単位・間隔・メタデータは保持する。
  await page.locator('#fileInput').setInputFiles({name:'custom.txt',mimeType:'text/plain',buffer:Buffer.from('format=stepscore,version=1,step_ms=1234,steps_per_quarter=7,title=カスタム,extra=保つ,source=https://example.com/score,work_id=custom,listen=https://example.com/listen,detail=説明,composer=作曲者,composer_ja=作曲者,composer_en=Composer,arranged_for=musicbox30,reading_ja=かすたむ,category=classical-folk,time_signature=3/4\nC-1,C5,G9\n\n')});await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='カスタム'&&document.querySelector('#cancelImport').hidden);assert.equal(await page.locator('#subdivision').inputValue(),'7');const custom=await save();assert.equal(custom.stepMs,1234);assert.equal(custom.length,2);assert.deepEqual(custom.notes,[{step:0,midi:72}]);assert.equal(custom.metadata.extra,'保つ');assert.deepEqual(Object.keys(custom.metadata).sort(),['format','version','step_ms','title','extra'].sort(),'取り込んだサンプル用・削除済み項目もプレビュー・コピー・TXTから除外');await page.locator('#copyText').click();assert.deepEqual(parseText(await page.evaluate(()=>navigator.clipboard.readText())),parseText(await preview.inputValue()));assert(await page.locator('#errorMessage').isHidden());await page.selectOption('#instrument','piano-88');assert.equal(await page.locator('#noteStats').textContent(),'3音 · 2ステップ','出力・楽器変更で編集中の音を削除しない');assert.equal((await save()).notes.length,1);await page.selectOption('#instrument','musicbox-30');
  await page.selectOption('#language','en');await page.waitForFunction(()=>document.documentElement.lang==='en');assert.equal(await page.locator('#subdivision option:checked').textContent(),'7 steps per quarter');await page.selectOption('#language','ja');await page.waitForFunction(()=>document.documentElement.lang==='ja');await page.locator('#reset').click();
  for(const bank of JSON.parse(await readFile('dist/audio/soundsets.json','utf8')).filter(bank=>bank.id!=='musicbox-30')){
    const count=await page.evaluate(async bank=>{const context=new AudioContext({sampleRate:44100});let count=0;try{for(const [note,file] of Object.entries(bank.files)){const response=await fetch(bank.base+encodeURIComponent(file)+'?v='+bank.revision);if(!response.ok)throw new Error(note+'を読み込めません');const buffer=await context.decodeAudioData(await response.arrayBuffer());if(buffer.numberOfChannels!==2||buffer.sampleRate!==44100||buffer.duration<=0)throw new Error(note+'の音声が不正です');count++;}}finally{await context.close();}return count;},bank);assert.equal(count,Object.keys(bank.files).length,bank.id+'の全音をブラウザでデコードできる');
  }
  await page.selectOption('#instrument','piano-88');await page.locator('#fileInput').setInputFiles({name:'piano-check.txt',mimeType:'text/plain',buffer:Buffer.from('format=stepscore,version=1,step_ms=250,title=ピアノ確認\nA0\nC4,E4,G4\nA4\nC8\nC#5\n\n\n\n')});await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='ピアノ確認'&&document.querySelector('#cancelImport').hidden);const pianoText=await preview.inputValue();await page.locator('#play').click();await page.waitForSelector('.step-label.playing');assert(await page.locator('#errorMessage').isHidden());await page.locator('#play').click();
  for(const [button,extension] of [['exportOgg','ogg'],['exportMp3','mp3']]){await page.locator('#save').click();const pending=page.waitForEvent('download');await page.locator('#'+button).click();const download=await pending;await download.saveAs('.sites-runtime/piano-check.'+extension);assert((await readFile(await download.path())).length>10000);assert.equal(await preview.inputValue(),pianoText,'録音ピアノの音声書き出しで楽譜を変更しない');assert(await page.locator('#errorMessage').isHidden());}
  await page.selectOption('#instrument','piano-61');assert.equal(await page.locator('.grid-row[data-midi]').count(),61);assert.deepEqual(await page.locator('.grid-row[data-midi]').evaluateAll(rows=>rows.map(row=>Number(row.dataset.midi))),Array.from({length:61},(_,i)=>96-i));assert(await page.locator('#rollViewport').evaluate(element=>element.scrollHeight<=element.clientHeight),'61鍵でも内部の縦スクロールなし');
  await page.locator('#fileInput').setInputFiles({name:'piano-61-check.txt',mimeType:'text/plain',buffer:Buffer.from('format=stepscore,version=1,step_ms=125,title=61鍵確認\nB1\nC2\nC5\nC7\nC#7\n')});await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='61鍵確認'&&document.querySelector('#cancelImport').hidden);assert.deepEqual(parseText(await preview.inputValue()).notes.map(note=>note.midi),[36,72,96],'61鍵はC2とC7を含み、上下の範囲外音だけ除く');
  const sharedPiano=page.waitForResponse(response=>response.url().includes('/audio/vsco-piano/C2.ogg'));await page.locator('.key-preview[data-midi="36"]').click();assert.equal((await sharedPiano).status(),200,'61鍵も同じ録音ピアノを使用');
  await page.locator('#save').click();const piano61MidiPending=page.waitForEvent('download');await page.locator('#exportMidi').click();const piano61Midi=new Midi(await readFile(await (await piano61MidiPending).path()));assert.equal(piano61Midi.tracks[0].instrument.number,0,'61鍵のMIDIもピアノの音色');assert.deepEqual(piano61Midi.tracks[0].notes.map(note=>note.midi),[36,72,96]);await page.selectOption('#instrument','piano-88');assert.equal(parseText(await preview.inputValue()).notes.length,5,'61鍵で除外した音も編集データに保持');
  for(const [id,program] of [['marimba-61',12],['xylophone-32',13]]){
    const profile=profiles.find(item=>item.id===id),[lo,hi]=profile.range,checkNotes=[lo-1,lo,lo+1,hi,hi+1],title=profile.name.ja;
    await page.selectOption('#instrument',id);assert.deepEqual(await page.locator('.grid-row[data-midi]').evaluateAll(rows=>rows.map(row=>Number(row.dataset.midi))),Array.from({length:hi-lo+1},(_,i)=>hi-i));assert(await page.locator('#rollViewport').evaluate(element=>element.scrollHeight<=element.clientHeight),'マリンバ・木琴も縦スクロールなし');
    await page.locator('#fileInput').setInputFiles({name:id+'.txt',mimeType:'text/plain',buffer:Buffer.from('format=stepscore,version=1,step_ms=125,title='+title+'\n'+checkNotes.map(note=>noteName(note)).join('\n')+'\n')});await page.waitForFunction(title=>document.querySelector('#scoreTitle').value===title&&document.querySelector('#cancelImport').hidden,title);
    const exported=parseText(await preview.inputValue());assert.deepEqual(exported.notes.map(note=>note.midi),[lo,lo+1,hi],'音域の両端を含み、上下の範囲外だけ省く');assert.equal(exported.length,5);
    const tone=page.waitForResponse(response=>response.url().includes('/audio/'+profile.defaultSoundset+'/'+noteName(lo)+'.ogg'));await page.locator('.key-preview[data-midi="'+lo+'"]').click();assert.equal((await tone).status(),200,'選択した楽器の専用音源を使用');await page.locator('#play').click();await page.waitForSelector('.step-label.playing');assert(await page.locator('#errorMessage').isHidden());await page.locator('#play').click();
    await page.locator('#save').click();const pending=page.waitForEvent('download');await page.locator('#exportMidi').click();const midi=new Midi(await readFile(await (await pending).path()));assert.equal(midi.tracks[0].instrument.number,program,'MIDIも選択した楽器の音色');assert.deepEqual(midi.tracks[0].notes.map(note=>note.midi),[lo,lo+1,hi]);
    await page.locator('#save').click();const audioPending=page.waitForEvent('download');await page.locator('#exportOgg').click();const audio=await audioPending;assert((await readFile(await audio.path())).length>1000,'楽器の録音音源で音声を書き出せる');assert.deepEqual(parseText(await preview.inputValue()),exported,'試聴・音声出力で楽譜を変更しない');
    await page.selectOption('#instrument','piano-88');assert.equal(parseText(await preview.inputValue()).notes.length,id==='xylophone-32'?4:5,'非対応音を編集データから削除しない');
  }
  await page.selectOption('#instrument','musicbox-30');await page.locator('#reset').click();
  // 基本名がないTXTは他言語の表示名を基本名にし、改名時は未知の言語名も取り除く。
  await page.locator('#fileInput').setInputFiles({name:'titles.txt',mimeType:'text/plain',buffer:Buffer.from(serialize([],1,125,{title_fr:'Nom français'}))});await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='Nom français'&&document.querySelector('#cancelImport').hidden);assert.equal(parseText(await preview.inputValue()).metadata.title,'Nom français');await page.locator('#scoreTitle').fill('自分の曲');await page.locator('#scoreTitle').press('Enter');assert.deepEqual(Object.keys(parseText(await preview.inputValue()).metadata).sort(),['format','version','step_ms','title'].sort());await page.selectOption('#language','en');await page.waitForFunction(()=>document.documentElement.lang==='en');assert.equal(await page.locator('#scoreTitle').inputValue(),'自分の曲');await page.selectOption('#language','ja');await page.waitForFunction(()=>document.documentElement.lang==='ja');await page.keyboard.press('Control+z');assert.equal(parseText(await preview.inputValue()).metadata.title_fr,'Nom français');await page.locator('#reset').click();
  await page.locator('#scoreTitle').fill('新しく付けた名前');await page.locator('#scoreTitle').press('Enter');assert.equal(parseText(await preview.inputValue()).metadata.title,'新しく付けた名前');await page.selectOption('#language','en');await page.waitForFunction(()=>document.documentElement.lang==='en');assert.equal(await page.locator('#scoreTitle').inputValue(),'新しく付けた名前');await page.selectOption('#language','ja');await page.waitForFunction(()=>document.documentElement.lang==='ja');await page.locator('#reset').click();
  // 表示BPMから間隔を再計算すると1234msが1224msになるケース。移調・単位変更は元のmsを使う。
  await page.locator('#fileInput').setInputFiles({name:'tempo.txt',mimeType:'text/plain',buffer:Buffer.from('format=stepscore,version=1,step_ms=1234,steps_per_quarter=7\nC5\n\n')});await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='tempo'&&document.querySelector('#cancelImport').hidden);assert.equal(await tempo.inputValue(),'7');assert.equal(parseText(await page.locator('#txtPreview').inputValue()).stepMs,1234);
  await transpose(1);assert.equal(parseText(await page.locator('#txtPreview').inputValue()).notes[0].midi,73);assert.equal(parseText(await page.locator('#txtPreview').inputValue()).stepMs,1234,'移調で丸めたBPMを再適用しない');
  await page.selectOption('#subdivision','4');await page.waitForFunction(()=>document.querySelector('#cancelImport').hidden);assert.equal(parseText(await page.locator('#txtPreview').inputValue()).stepMs,2160,'ステップ単位は元のmsから換算');assert.equal(await tempo.inputValue(),'7');await page.locator('#reset').click();
  const rangeNotes=[{step:0,midi:72},{step:4,midi:66},{step:5,midi:127},{step:8,midi:76},{step:12,midi:79},{step:20,midi:84}];
  await page.locator('#fileInput').setInputFiles({name:'range.txt',mimeType:'text/plain',buffer:Buffer.from(serialize(rangeNotes,24,125,{steps_per_quarter:'4',time_signature:'4/4',extra:'保つ'}))});await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='range'&&document.querySelector('#cancelImport').hidden);
  const header=step=>page.locator(`.step-label[data-step="${step}"]`),visibleScore=()=>page.locator('#txtPreview').inputValue().then(parseText),dragHeaders=async(first,last)=>{await header(first).scrollIntoViewIfNeeded();const a=await header(first).boundingBox(),b=await header(last).boundingBox();await page.mouse.move(a.x+4,a.y+a.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width-4,b.y+b.height/2,{steps:12});await page.mouse.up();};
  await header(7).click();assert.equal(await page.locator('.step-label.selected').getAttribute('data-step'),'7','クリックしたマスを再生開始位置にする');assert(await page.locator('#deleteRange').isDisabled());assert.equal(await page.locator('.step-label.time-selected').count(),0,'クリックだけでは範囲を選択しない');await page.locator('#play').click();await page.waitForFunction(()=>Number(document.querySelector('.step-label.playing')?.dataset.step)>=7);await page.locator('#play').click();assert.equal(await page.locator('.step-label.selected').getAttribute('data-step'),'0','停止は以前と同じく先頭に戻る');
  await dragHeaders(3,13);await page.locator('#deleteRange').click();let cut=await visibleScore();assert.equal(cut.length,24,'通常の削除はマス目を残す');assert.equal(cut.stepMs,125);assert.equal(cut.metadata.extra,'保つ');assert.deepEqual(cut.notes,[{step:0,midi:72},{step:20,midi:84}],'後続音の位置を保つ');assert.equal(await page.locator('#noteStats').textContent(),'2音 · 24ステップ','非対応・非表示の音も消す');assert(await page.locator('#midiPanel').isHidden());assert(await page.locator('#unsupportedPanel').isHidden());await page.keyboard.press('Control+z');assert.equal(await page.locator('#noteStats').textContent(),'6音 · 24ステップ');assert(!(await page.locator('#midiPanel').isHidden()));
  await dragHeaders(4,4);assert.equal(await page.locator('.step-label.time-selected').count(),1);assert.equal(await page.locator('.cell.time-selected').count(),41);await page.locator('#collapseRange').click();cut=await visibleScore();assert.equal(cut.length,23);assert.equal(cut.stepMs,125);assert.equal(cut.metadata.extra,'保つ');assert.deepEqual(cut.notes,[{step:0,midi:72},{step:7,midi:76},{step:11,midi:79},{step:19,midi:84}]);assert.equal(await page.locator('#noteStats').textContent(),'5音 · 23ステップ','削除は選択した1ステップだけ');assert(await page.locator('#midiPanel').isHidden());
  await page.keyboard.press('Control+z');assert.equal(await page.locator('#noteStats').textContent(),'6音 · 24ステップ');assert(!(await page.locator('#midiPanel').isHidden()));assert.equal(await page.locator('#exportWarning').textContent(),'非対応：2音（再生・出力から除外）','取り消しで非対応音の数も復元');
  for(const key of ['Delete','Backspace']){
    await dragHeaders(3,13);await page.keyboard.press(key);cut=await visibleScore();assert.equal(cut.length,24,`${key}では時間を詰めない`);assert.deepEqual(cut.notes,[{step:0,midi:72},{step:20,midi:84}]);assert.equal(cut.stepMs,125);assert.equal(cut.metadata.extra,'保つ');assert(await page.locator('#deleteRange').isDisabled());assert(await page.locator('#collapseRange').isDisabled());assert(await page.locator('#midiPanel').isHidden());await page.keyboard.press('Control+z');assert.equal(await page.locator('#noteStats').textContent(),'6音 · 24ステップ');assert(!(await page.locator('#midiPanel').isHidden()));
  }
  await dragHeaders(3,13);const beforeTyping=await visibleScore(),title=page.locator('#scoreTitle'),originalTitle=await title.inputValue();await title.focus();await title.press('End');await title.press('Backspace');assert.equal(await title.inputValue(),originalTitle.slice(0,-1),'入力欄のBackspaceは文字を消す');assert.deepEqual(await visibleScore(),{...beforeTyping,metadata:{...beforeTyping.metadata,title:originalTitle.slice(0,-1)}},'入力欄では曲名だけ変更し、選択区間を削除しない');assert.equal(await page.locator('.step-label.time-selected').count(),11);await title.fill(originalTitle);await header(3).focus();
  for(const key of ['Control+Delete','Alt+Delete']){await page.keyboard.press(key);assert.deepEqual(await visibleScore(),beforeTyping);assert.equal(await page.locator('.step-label.time-selected').count(),11);}
  await header(3).dispatchEvent('keydown',{key:'Delete',isComposing:true});assert.deepEqual(await visibleScore(),beforeTyping,'IME入力中は区間を削除しない');await page.keyboard.press('Escape');
  await dragHeaders(13,3);assert.equal(await page.locator('.step-label.time-selected').first().getAttribute('data-step'),'3');assert.equal(await page.locator('.step-label.time-selected').count(),11,'拍の途中から右から左へ選択');assert.equal(await page.locator('.step-label.selected').getAttribute('data-step'),'13','範囲の始点を広げても再生開始位置を動かさない');await page.keyboard.press('Shift+Backspace');cut=await visibleScore();assert.equal(cut.length,13);assert.deepEqual(cut.notes,[{step:0,midi:72},{step:9,midi:84}],'後続音と末尾休符を同じ幅だけ詰める');assert.equal(await page.locator('#noteStats').textContent(),'2音 · 13ステップ','非対応音と非表示のG9も区間ごと削除');await page.keyboard.press('Control+z');assert.equal(await page.locator('#noteStats').textContent(),'6音 · 24ステップ');
  await header(8).dblclick();assert.equal(await page.locator('.step-label.time-selected').count(),0,'ダブルクリックでも小節を選ばない');assert.equal(await page.locator('.step-label.selected').getAttribute('data-step'),'8');
  await header(0).click();await header(0).press('ArrowRight');assert.equal(await page.locator('.step-label.selected').getAttribute('data-step'),'1','矢印も1ステップずつ移動');await dragHeaders(5,9);await page.keyboard.press('Escape');assert(await page.locator('#deleteRange').isDisabled());assert.equal(await page.locator('.step-label.selected').getAttribute('data-step'),'5','範囲を解除してもクリックした開始位置は保つ');
  await dragHeaders(0,23);await page.locator('#deleteRange').click();cut=await visibleScore();assert.equal(cut.length,24);assert.equal(cut.notes.length,0,'全範囲の通常削除は休符として残す');await page.keyboard.press('Control+z');assert.equal(await page.locator('#noteStats').textContent(),'6音 · 24ステップ');
  await dragHeaders(0,23);await page.keyboard.press('Shift+Delete');cut=await visibleScore();assert.equal(cut.length,1);assert.equal(cut.notes.length,0,'全区間を詰めて削除すると空の1ステップを残す');await page.keyboard.press('Control+z');assert.equal(await page.locator('#noteStats').textContent(),'6音 · 24ステップ');
  const tripleNotes=[{step:0,midi:72},{step:2,midi:76},{step:14,midi:79},{step:21,midi:84}];await page.locator('#fileInput').setInputFiles({name:'triple.txt',mimeType:'text/plain',buffer:Buffer.from(serialize(tripleNotes,22,172,{steps_per_quarter:'4',time_signature:'3/4'}))});await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='triple'&&document.querySelector('#cancelImport').hidden);
  await dragHeaders(20,21);assert.equal(await page.locator('.step-label.time-selected').count(),2,'3拍子でもステップ単位');await page.locator('#collapseRange').click();cut=await visibleScore();assert.equal(cut.length,20);assert.equal(cut.stepMs,172);assert(!('time_signature' in cut.metadata));assert(await header(12).evaluate(element=>element.classList.contains('bar')),'編集中の3拍子の小節線は区間削除後も保つ');assert.deepEqual(cut.notes,tripleNotes.slice(0,3));await page.keyboard.press('Control+z');assert.deepEqual((await visibleScore()).notes,tripleNotes);
  const elise=parseText(await readFile('dist/samples/fur-elise-musicbox-30.txt','utf8'));await chooseTemplate('fur-elise-musicbox-30');await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='エリーゼのために');const eliseOutput=await visibleScore();assert.deepEqual([eliseOutput.notes,eliseOutput.length,eliseOutput.stepMs],[elise.notes,elise.length,elise.stepMs],'導入の音と再生間隔は変えない');await header(1).click();assert.equal(await page.locator('.step-label.selected').getAttribute('data-step'),'1','拍の途中のマスも開始位置にできる');await dragHeaders(1,4);assert.equal(await page.locator('.step-label.time-selected').first().getAttribute('data-step'),'1');assert.equal(await page.locator('.step-label.time-selected').count(),4,'3/8でも拍・小節に丸めない');
  await chooseTemplate('pachelbel-canon-musicbox-30');await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='カノン');await page.screenshot({path:'.sites-runtime/refactor-desktop.png',fullPage:true});
  await dragHeaders(3,31);await page.screenshot({path:'.sites-runtime/range-selection.png',fullPage:true});await page.evaluate(()=>{document.querySelector('#rollViewport').scrollLeft=600;});await page.waitForSelector('.step-label[data-step="50"]',{state:'attached'});assert(await page.locator('.step-label.time-selected').count()>0,'仮想描画で選択区間を保持');assert(await page.locator('#deleteRange').isEnabled());await page.evaluate(()=>{document.querySelector('#rollViewport').scrollLeft=0;});await page.waitForSelector('.step-label[data-step="0"]',{state:'attached'});assert.equal(await page.locator('.step-label.time-selected').count(),29);await page.keyboard.press('Escape');
  await page.setViewportSize({width:390,height:844});assert(await page.locator('#rollViewport').evaluate(element=>element.scrollHeight<=element.clientHeight),'モバイルでも鍵盤を縦スクロールしない');await page.locator('#txtPreviewPanel summary').click();assert(await preview.evaluate(element=>element.scrollWidth<=element.clientWidth),'モバイルでも長いヘッダーを折り返す');await page.screenshot({path:'.sites-runtime/refactor-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'モバイルでページ全体が横にはみ出さない');
  // 新規入力・サンプル・TXT・MIDIを共通の移調操作で編集する。
  await page.setViewportSize({width:1280,height:900});await page.selectOption('#instrument','piano-88');await page.locator('#reset').click();
  await page.locator('.cell[data-step="0"][data-midi="72"]').click();await page.locator('.cell[data-step="2"][data-midi="76"]').click();const manual=await visibleScore();
  await transpose(12);assert.deepEqual((await visibleScore()).notes,[{step:0,midi:84},{step:2,midi:88}]);await page.keyboard.press('Control+z');assert.deepEqual(await visibleScore(),manual,'Shift＋クリックの1オクターブ移調を1回の取り消しで戻す');
  await page.locator('.cell[data-step="0"][data-midi="72"]').click({modifiers:['Shift']});await transpose(-12);assert.deepEqual((await visibleScore()).notes,[{step:0,midi:60},{step:2,midi:76}],'選択音だけを移調');await transpose(12);assert.deepEqual(await visibleScore(),manual,'移調後も選択を保ち、相対移調を続けられる');await page.keyboard.press('Control+z');await page.keyboard.press('Control+z');assert.deepEqual(await visibleScore(),manual);
  await chooseTemplate('pachelbel-canon-musicbox-30');await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='カノン');const sampleBefore=await visibleScore();await transpose(1);assert.deepEqual(await visibleScore(),{...sampleBefore,notes:sampleBefore.notes.map(note=>({...note,midi:note.midi+1}))},'サンプルの長さ・間隔・曲名を保って移調');await page.keyboard.press('Control+z');assert.deepEqual(await visibleScore(),sampleBefore);
  const loadShiftText=async(score,size=8)=>{await page.locator('#fileInput').setInputFiles({name:'transpose-check.txt',mimeType:'text/plain',buffer:Buffer.from(serialize(score,size,137,{title:'移調確認',extra:'保持'}))});await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='移調確認'&&document.querySelector('#cancelImport').hidden);};
  await loadShiftText([{step:0,midi:72},{step:0,midi:73},{step:4,midi:76}]);const collisionBefore=await visibleScore();await page.locator('.cell[data-step="0"][data-midi="72"]').click({modifiers:['Shift']});await transpose(1);assert.deepEqual((await visibleScore()).notes,[{step:0,midi:73},{step:4,midi:76}],'移調先と重なる音を統合');assert(await page.locator('#midiPanel').isHidden(),'部分移調後は取り込み元との連動を外す');await page.keyboard.press('Control+z');assert.deepEqual(await visibleScore(),collisionBefore);assert(await page.locator('#midiPanel').isVisible());
  await dragHeaders(0,1);await transpose(12);assert.deepEqual((await visibleScore()).notes,[{step:0,midi:84},{step:0,midi:85},{step:4,midi:76}],'選択ステップ内の全音を移調');assert.equal(await page.locator('.step-label.time-selected').count(),2,'移調後も範囲選択を保つ');assert.equal((await visibleScore()).metadata.extra,'保持');assert.equal((await visibleScore()).stepMs,137);await page.keyboard.press('Control+z');assert.deepEqual(await visibleScore(),collisionBefore);
  await loadShiftText([{step:0,midi:20},{step:1,midi:21},{step:2,midi:72},{step:3,midi:108},{step:4,midi:109}]);await transpose(1);assert.deepEqual((await visibleScore()).notes,[{step:0,midi:21},{step:1,midi:22},{step:2,midi:73}],'非表示の音も移調し、楽器の範囲外の音は保持');await transpose(-1);assert.equal(await page.locator('#noteStats').textContent(),'5音 · 8ステップ');assert.deepEqual((await visibleScore()).notes,[{step:1,midi:21},{step:2,midi:72},{step:3,midi:108}]);
  await loadShiftText([{step:0,midi:0},{step:1,midi:72},{step:2,midi:127}]);const boundaryBefore=await visibleScore();
  for(const amount of [1,-1,12,-12]){await transpose(amount);assert.deepEqual(await visibleScore(),boundaryBefore,'通常クリック・Shift＋クリックともに非表示音を含むMIDI音域を確認して全音を保持');assert(await page.locator('#errorMessage').isVisible());}
  await page.keyboard.press('Control+z');assert.equal(await page.locator('#noteStats').textContent(),'5音 · 8ステップ','失敗時に履歴を追加しない');
  const shiftMidi=new Midi();for(const midi of [48,52])shiftMidi.addTrack().addNote({midi,ticks:0,durationTicks:480});await page.locator('#fileInput').setInputFiles({name:'transpose-check.mid',mimeType:'audio/midi',buffer:Buffer.from(shiftMidi.toArray())});await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='transpose-check'&&document.querySelector('#cancelImport').hidden);const importWorkers=requests.filter(url=>/\/import-worker\.js(?:\?|$)/.test(url)).length;
  await transpose(12);await transpose(24);assert.deepEqual((await visibleScore()).notes.map(note=>note.midi),[84,88]);await page.locator('#trackSummary').click();await page.locator('#trackList input[value="1"]').uncheck();await page.waitForFunction(()=>document.querySelector('#cancelImport').hidden);assert.deepEqual((await visibleScore()).notes.map(note=>note.midi),[84],'トラック変更後も累積36半音の移調を保持');await page.selectOption('#subdivision','8');await page.waitForFunction(()=>document.querySelector('#cancelImport').hidden);assert.deepEqual((await visibleScore()).notes.map(note=>note.midi),[84]);await page.locator('#trackList input[value="1"]').check();await page.waitForFunction(()=>document.querySelector('#cancelImport').hidden);assert.deepEqual((await visibleScore()).notes.map(note=>note.midi),[84,88]);
  assert.equal(requests.filter(url=>/\/import-worker\.js(?:\?|$)/.test(url)).length,importWorkers,'全体移調後のトラック・単位変更でも解析済みWorkerを再利用する');
  await page.locator('.cell[data-step="3"][data-midi="90"]').click();await page.locator('.cell[data-step="0"][data-midi="84"]').click({modifiers:['Shift']});await page.locator('#suggest').click();assert.deepEqual((await visibleScore()).notes,[{step:0,midi:48},{step:0,midi:52},{step:3,midi:54}],'おすすめも現在の全音を移調し、後から追加した音を失わない');await page.keyboard.press('Control+z');await page.waitForFunction(()=>document.querySelector('#suggest').dataset.transpose==='-36');assert.deepEqual((await visibleScore()).notes.map(note=>note.midi),[84,88,90],'おすすめを1回で取り消す');
  await page.locator('.cell[data-step="0"][data-midi="84"]').click({modifiers:['Shift']});await transpose(-1);assert(await page.locator('#midiPanel').isHidden());assert.deepEqual((await visibleScore()).notes.map(note=>note.midi),[83,88,90]);await page.keyboard.press('Control+z');assert(await page.locator('#midiPanel').isVisible());assert.deepEqual((await visibleScore()).notes.map(note=>note.midi),[84,88,90]);
  for(const language of ['ja','en']){await page.selectOption('#language',language);await page.waitForFunction(lang=>document.documentElement.lang===lang,language);await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('.transpose-actions>span').textContent(),language==='ja'?'移調':'Transpose');assert.equal(await page.locator('#transposeUp').getAttribute('title'),language==='ja'?'半音上げる（Shiftで1オクターブ）':'Up a semitone (Shift: octave)');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const beforeKeys=await visibleScore();for(const [id,key,amount]of [['transposeUp','Enter',1],['transposeDown','Space',-1]]){await page.locator('#'+id).press(key);assert.deepEqual((await visibleScore()).notes,beforeKeys.notes.map(note=>({...note,midi:note.midi+amount})),'Enter・Spaceで直接移調');await page.keyboard.press('Control+z');assert.deepEqual(await visibleScore(),beforeKeys);}}
  const beforeEmpty=await visibleScore();await page.locator('#reset').click();await transpose(12);assert.equal((await visibleScore()).notes.length,0);await page.keyboard.press('Control+z');assert.deepEqual(await visibleScore(),beforeEmpty,'空の楽譜の移調は履歴を追加しない');
  const mobile=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true,locale:'ja-JP'});mobile.on('pageerror',error=>errors.push(error.message));await mobile.goto(process.argv[2]??'http://127.0.0.1:4173');await mobile.waitForSelector('#instrument option',{state:'attached'});await mobile.locator('.step-label[data-step="4"]').tap();assert.equal(await mobile.locator('.step-label.selected').getAttribute('data-step'),'4');assert.equal(await mobile.locator('.step-label.time-selected').count(),0);assert(await mobile.locator('#deleteRange').isDisabled());
  await mobile.locator('#fileInput').setInputFiles({name:'touch.txt',mimeType:'text/plain',buffer:Buffer.from(serialize([{step:0,midi:72},{step:10,midi:76}],32,125))});await mobile.waitForFunction(()=>document.querySelector('#scoreTitle').value==='touch'&&document.querySelector('#cancelImport').hidden);
  await mobile.locator('#transposeUp').tap();assert.deepEqual(parseText(await mobile.locator('#txtPreview').inputValue()).notes,[{step:0,midi:73},{step:10,midi:77}],'タップで半音上げる');await mobile.locator('#transposeDown').tap();assert.deepEqual(parseText(await mobile.locator('#txtPreview').inputValue()).notes,[{step:0,midi:72},{step:10,midi:76}],'タップで半音下げる');
  const touchSession=await mobile.context().newCDPSession(mobile),touchA=await mobile.locator('.step-label[data-step="0"]').boundingBox(),touchB=await mobile.locator('.step-label[data-step="8"]').boundingBox();await touchSession.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touchA.x+15,y:touchA.y+14}]});for(let i=1;i<=8;i++)await touchSession.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:touchA.x+15+(touchB.x-touchA.x)*i/8,y:touchA.y+14}]});await touchSession.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await mobile.locator('.step-label.time-selected').count(),9,'タッチでもステップ単位で選ぶ');
  // Chromiumの合成タッチはドラッグ直後のタップを無視するため、ジェスチャーの終了を待つ。
  await new Promise(resolve=>setTimeout(resolve,1000));await mobile.locator('#deleteRange').tap();await mobile.waitForFunction(()=>document.querySelector('#noteStats').textContent==='1音 · 32ステップ');const touchScore=parseText(await mobile.locator('#txtPreview').inputValue());assert.equal(touchScore.length,32);assert.deepEqual(touchScore.notes,[{step:10,midi:76}],'タップで音だけ消し、後続音の位置を保つ');await mobile.close();
  assert(!errors.length,errors.join('\n'));console.log('ブラウザ確認成功：共通移調・選択音・重複統合・音域検証・MIDI連動・保存・再取り込み・言語・楽器・試聴・ステップ範囲削除・取り消し・Worker中止・モバイル');
}finally{await browser.close();}
