import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import {dirname,resolve} from 'node:path';
import {pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
import {parseText,noteNumber,definitionNotes} from './dist/core.js';
const catalog=JSON.parse(await readFile('dist/samples/index.json','utf8')),profiles=JSON.parse(await readFile('dist/instruments.json','utf8')),allowed=definitionNotes(profiles[0]);
// 依存関係は追加しない。既存のPlaywright、またはCodex同梱ランタイムで実行する。
let automation;try{automation=await import('playwright');}catch{automation=await import(pathToFileURL(resolve(dirname(process.execPath),'../node_modules/playwright/index.mjs')));}
const browser=await automation.chromium.launch({headless:true,...(process.platform==='win32'?{channel:'msedge'}:{})});
const errors=[],requests=[];
await mkdir('.sites-runtime',{recursive:true});
try{
  const page=await browser.newPage({viewport:{width:1280,height:900}});page.setDefaultTimeout(15000);
  page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>requests.push(request.url()));
  await page.goto(process.argv[2]??'http://127.0.0.1:4173');await page.waitForSelector('#instrument option',{state:'attached'});
  assert.equal(await page.locator('#status').count(),0);assert(await page.locator('#errorMessage').isHidden());assert.equal(await page.locator('#timeSelectionStats').count(),0);assert.equal(await page.locator('#copyText').textContent(),'テキストでコピー');assert.equal(await page.locator('#copyText').getAttribute('title'),'StepScore形式のテキストでコピー');assert.equal(await page.locator('#roll').getAttribute('title'),'Shift＋クリック：選択、ドラッグ：選択・移動');assert.equal(await page.locator('#deleteRange').textContent(),'削除');assert.equal(await page.locator('#deleteRange').getAttribute('title'),'Delete / Backspace');assert.equal(await page.locator('#collapseRange').textContent(),'削除して詰める');assert.equal(await page.locator('#collapseRange').getAttribute('title'),'Shift + Delete / Backspace');assert(await page.locator('#collapseRange').isDisabled());
  assert.equal(await page.locator('#noteStats').textContent(),'0音 · 32ステップ');assert.deepEqual(await page.locator('#templateSelect option').evaluateAll(options=>options.map(option=>option.value).filter(Boolean).sort()),catalog.samples.filter(item=>item.usedNotes.every(note=>allowed.has(note))).map(item=>item.id).sort());
  assert(!requests.some(url=>/vendor\/midi|\.ogg(?:\?|$)|\/samples\/[^/]+\.txt/.test(url)),'初期表示でMIDIライブラリ・全音源・全曲を読み込まない');
  assert(await page.locator('#rollViewport').evaluate(element=>element.scrollHeight<=element.clientHeight),'30音の鍵盤を縦スクロールなしで展開');await page.locator('.cell[data-step="0"][data-midi="72"]').hover();const beforeWheel=await page.evaluate(()=>scrollY);await page.mouse.wheel(0,200);await page.waitForFunction(before=>scrollY>before,beforeWheel);
  await page.selectOption('#templateSelect','pachelbel-canon-musicbox-30');await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='カノン');
  const canon=parseText(await page.locator('#txtPreview').inputValue()),canonSource=parseText(await readFile('dist/samples/pachelbel-canon-musicbox-30.txt','utf8'));assert.equal(canon.length,canonSource.length);assert.deepEqual(canon.notes,canonSource.notes);assert.deepEqual(canon.metadata,Object.fromEntries(Object.entries(canonSource.metadata).filter(([key])=>['format','version','step_ms','title'].includes(key)||key.startsWith('title_'))),'基本名・表示名を保ち、サンプル管理用の項目を含めない');
  const preview=page.locator('#txtPreview'),canonText=await preview.inputValue();assert.equal(canonText.split('\n').length,canon.length+2,'ヘッダーと各ステップの改行を保持');assert(!canonText.includes('\r'),'プレビューの改行はLF');await page.locator('#txtPreviewPanel summary').click();assert(await preview.evaluate(element=>element.scrollWidth<=element.clientWidth),'長いヘッダーを画面内で折り返す');assert.equal(await preview.inputValue(),canonText,'表示の折り返しをデータに加えない');await page.locator('#scoreTitle').fill('取消す曲名');await page.locator('#scoreTitle').press('Escape');assert.equal(await page.locator('#scoreTitle').inputValue(),'カノン');assert.equal(await preview.inputValue(),canonText,'曲名の取消しをプレビューにも反映');await page.locator('#scoreTitle').fill('確定した曲名');assert(!Object.keys(parseText(await preview.inputValue()).metadata).some(key=>key.startsWith('title_')),'入力中のプレビューでも改名時は翻訳名を省く');await page.locator('#scoreTitle').press('Enter');assert.equal(parseText(await preview.inputValue()).metadata.title,'確定した曲名');await page.keyboard.press('Control+z');assert.equal(await preview.inputValue(),canonText,'曲名の取り消しも元のプレビューに戻す');await page.locator('#txtPreviewPanel summary').click();
  const tempo=page.locator('#bpm');assert.equal(await tempo.inputValue(),'55');assert.equal(canon.stepMs,136,'整数表示でも元の136msを保持');
  await tempo.press('ArrowUp');await tempo.press('Tab');assert.equal(await tempo.inputValue(),'56');assert.equal(parseText(await page.locator('#txtPreview').inputValue()).stepMs,134);
  await tempo.press('ArrowDown');await tempo.press('Tab');assert.equal(await tempo.inputValue(),'55');
  await tempo.fill('55.6');await tempo.press('Tab');assert.equal(await tempo.inputValue(),'56','手入力の小数も確定時に整数化');await tempo.fill('55');await tempo.press('Tab');
  await page.selectOption('#language','en');await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='Canon');assert.match(await page.locator('#noteStats').textContent(),/notes.*steps/);assert.deepEqual(parseText(await preview.inputValue()).metadata,canon.metadata,'言語切り替えでは基本名と翻訳名を保持');
  assert.equal(await page.locator('#copyText').textContent(),'Copy text');assert.equal(await page.locator('#copyText').getAttribute('title'),'Copy text in StepScore format');assert.equal(await page.locator('#deleteRange').textContent(),'Delete');assert.equal(await page.locator('#collapseRange').textContent(),'Delete & close gap');
  await page.locator('#scoreTitle').fill('My custom score');await page.locator('#bpm').click();await page.locator('#scoreTitle').fill('取消す別の曲名');await page.locator('#scoreTitle').press('Escape');assert.equal(parseText(await preview.inputValue()).metadata.title,'My custom score');await page.selectOption('#language','ja');await page.waitForFunction(()=>document.documentElement.lang==='ja');assert.equal(await page.locator('#scoreTitle').inputValue(),'My custom score');assert(!Object.keys(parseText(await preview.inputValue()).metadata).some(key=>key.startsWith('title_')));await page.keyboard.press('Control+z');assert.equal(await page.locator('#scoreTitle').inputValue(),'カノン','英語での改名を日本語で取り消すと日本語名へ戻す');assert.deepEqual(parseText(await preview.inputValue()).metadata,canon.metadata);await page.locator('#scoreTitle').fill('My custom score');await page.locator('#scoreTitle').press('Enter');
  await page.locator('.cell[data-step="1"][data-midi="66"]').click();assert.equal(await page.locator('.cell[data-step="1"][data-midi="66"]').getAttribute('aria-pressed'),'true');assert(await page.locator('#unsupportedPanel').isVisible());
  assert.equal(await page.locator('#exportWarning').textContent(),'非対応：1音（再生・出力から除外）');assert.equal(await page.locator('#removeUnsupported').textContent(),'非対応の音を削除');await page.context().grantPermissions(['clipboard-read','clipboard-write']);await page.locator('#copyText').click();assert.deepEqual(parseText(await page.evaluate(()=>navigator.clipboard.readText())),parseText(await page.locator('#txtPreview').inputValue()));assert(await page.locator('#errorMessage').isHidden(),'コピー完了の通知は表示しない');
  const save=async()=>{await page.locator('#save').click();const pending=page.waitForEvent('download');await page.locator('#export').click();const download=await pending,text=await readFile(await download.path(),'utf8');assert.equal(text,await preview.inputValue(),'TXT書き出しは折り返しを含まずプレビューの実データと一致');return parseText(text);};
  const instrumentText=await save();assert(!instrumentText.notes.some(note=>note.midi===66));assert.equal(instrumentText.length,canon.length);assert.equal(instrumentText.notes.length,canon.notes.length);
  await page.locator('#save').click();const midiPending=page.waitForEvent('download');await page.locator('#exportMidi').click();const midiFile=await midiPending,{Midi}=createRequire(import.meta.url)('@tonejs/midi'),exportedMidi=new Midi(await readFile(await midiFile.path()));assert.equal(exportedMidi.tracks[0].notes.length,instrumentText.notes.length);assert(!exportedMidi.tracks[0].notes.some(note=>note.midi===66));assert.deepEqual(exportedMidi.header.timeSignatures[0].timeSignature,[4,4],'MIDIはTXT出力で省いた拍子も編集中のデータから出力する');assert.equal(exportedMidi.tracks[0].controlChanges[123][0].ticks,instrumentText.length*exportedMidi.header.ppq/8);
  await page.selectOption('#instrument','piano-88');assert(await page.locator('#rollViewport').evaluate(element=>element.scrollHeight<=element.clientHeight),'88鍵でも縦スクロールなしで展開');assert.equal(await page.locator('#soundset').inputValue(),'vsco-piano');assert(!(await page.locator('#unsupportedPanel').isVisible()));assert(parseText(await page.locator('#txtPreview').inputValue()).notes.some(note=>note.midi===66));const saved=await save();assert(saved.notes.some(note=>note.midi===66),'88鍵の音はピアノを選んで書き出す');assert.equal(saved.notes.length,instrumentText.notes.length+1);assert.equal(saved.length,instrumentText.length);assert.equal(saved.metadata.title,'My custom score');
  const pianoResponse=page.waitForResponse(response=>response.url().includes('/audio/vsco-piano/C5.ogg'));await page.locator('.key-preview[data-midi="72"]').click();assert.equal((await pianoResponse).status(),200,'ピアノの鍵盤は録音を読み込む');assert.deepEqual(parseText(await preview.inputValue()),saved,'鍵盤の試聴で楽譜を変更しない');await page.selectOption('#soundset','basic');assert.deepEqual(parseText(await preview.inputValue()),saved,'音源を切り替えても楽譜を変更しない');await page.selectOption('#soundset','vsco-piano');
  await page.selectOption('#instrument','musicbox-30');assert(await page.locator('#unsupportedPanel').isVisible());
  // ピアノ用に書き出した音とメタデータを実際に再取り込みする。
  const {serialize}=await import('./dist/core.js');await page.locator('#fileInput').setInputFiles({name:'roundtrip.txt',mimeType:'text/plain',buffer:Buffer.from(serialize(saved.notes,saved.length,saved.stepMs,saved.metadata))});await page.waitForFunction(()=>!document.querySelector('#midiPanel').hidden&&document.querySelector('#cancelImport').hidden);
  assert.equal(await page.locator('#scoreTitle').inputValue(),'My custom score');await page.selectOption('#language','en');await page.waitForFunction(()=>document.documentElement.lang==='en');assert.equal(await page.locator('#scoreTitle').inputValue(),'My custom score');
  await page.selectOption('#instrument','piano-88');await page.waitForFunction(()=>document.querySelector('#suggest').textContent.includes('Recommended'));
  await page.selectOption('#subdivision','4');await page.waitForFunction(()=>document.querySelector('.step-label[data-step="4"]')?.textContent==='2'&&document.querySelector('#cancelImport').hidden);
  const before=parseText(await page.locator('#txtPreview').inputValue());
  await page.locator('#fileInput').setInputFiles('.sites-runtime/large-import-check.mid');await page.locator('#cancelImport').click();assert.deepEqual(parseText(await page.locator('#txtPreview').inputValue()).notes,before.notes,'中止で編集中の全音を保持');
  await page.evaluate(()=>{window.checkTicks=0;window.checkGap=0;window.checkLast=performance.now();window.checkTimer=setInterval(()=>{const now=performance.now();window.checkGap=Math.max(window.checkGap,now-window.checkLast);window.checkLast=now;window.checkTicks++;},25);});
  const began=performance.now();await page.locator('#fileInput').setInputFiles('.sites-runtime/large-import-check.mid');await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='large-import-check'&&document.querySelector('#cancelImport').hidden);
  const elapsed=performance.now()-began,performanceResult=await page.evaluate(()=>{clearInterval(window.checkTimer);return {ticks:window.checkTicks,maxGap:window.checkGap,...document.querySelector('#roll').dataset};});
  const large=parseText(await page.locator('#txtPreview').inputValue());assert.equal(large.notes.length,80000);assert.equal(large.length,16000);assert(Number(performanceResult.cells)<6000,'長さに比例する全マスを作らない');assert(performanceResult.ticks>2,'Worker解析中もメインスレッドが動く');
  console.log('ブラウザ：80,000音・16,000ステップ', {elapsedMs:elapsed,...performanceResult});
  await page.evaluate(()=>{const viewport=document.querySelector('#rollViewport');viewport.scrollLeft=viewport.scrollWidth;});await page.waitForSelector('.cell[data-step="15999"]',{state:'attached'});assert(await page.locator('.cell').count()<6000);
  await page.locator('#fileInput').setInputFiles({name:'broken.mid',mimeType:'audio/midi',buffer:Buffer.from('invalid')});await page.waitForFunction(()=>document.querySelector('#errorMessage').textContent!==''&&document.querySelector('#cancelImport').hidden);assert.deepEqual(parseText(await page.locator('#txtPreview').inputValue()).notes,large.notes,'失敗で現在の楽譜を保持');assert(!/[ぁ-んァ-ヶ一-龥]/.test(await page.locator('#errorMessage').textContent()),'英語エラー表示');
  await page.selectOption('#language','ja');await page.waitForFunction(()=>document.documentElement.lang==='ja');await page.locator('#reset').click();await page.selectOption('#instrument','musicbox-30');
  const cell=page.locator('.cell[data-step="0"][data-midi="72"]');await cell.scrollIntoViewIfNeeded();const start=await cell.boundingBox(),end=await page.locator('.cell[data-step="3"][data-midi="72"]').boundingBox();
  await page.mouse.move(start.x+start.width/2,start.y+start.height/2);await page.mouse.down();await page.mouse.move(end.x+end.width/2,end.y+end.height/2,{steps:12});await page.mouse.up();assert.equal(parseText(await page.locator('#txtPreview').inputValue()).notes.length,4,'押したまま連続入力');
  await page.keyboard.press('Control+z');assert.equal(parseText(await page.locator('#txtPreview').inputValue()).notes.length,0,'連続入力を1回で取り消し');
  await cell.click();await cell.click({modifiers:['Shift']});await cell.press('Shift+ArrowRight');assert.equal(parseText(await page.locator('#txtPreview').inputValue()).notes[0].step,1,'選択した音の移動');
  await page.keyboard.press('Control+z');assert.equal(parseText(await page.locator('#txtPreview').inputValue()).notes[0].step,0);
  await page.selectOption('#soundset','musicbox-30');await page.locator('#play').click();await page.waitForSelector('.step-label.playing');assert(await page.locator('#errorMessage').isHidden(),'試聴中の通知は表示しない');await page.locator('#play').click();assert(await page.locator('#errorMessage').isHidden(),'停止時の通知は表示しない');assert(requests.some(url=>url.includes('/audio/musicbox-30/C5.ogg')),'移動した録音を実際に読み込み・デコードする');assert(!errors.length,errors.join('\n'));
  // 88鍵外の音は編集データに保持し、出力は対応音だけ。独自の単位・間隔・メタデータは保持する。
  await page.locator('#fileInput').setInputFiles({name:'custom.txt',mimeType:'text/plain',buffer:Buffer.from('format=stepscore,version=1,step_ms=1234,steps_per_quarter=7,title=カスタム,extra=保つ,source=https://example.com/score,work_id=custom,listen=https://example.com/listen,detail=説明,composer=作曲者,composer_ja=作曲者,composer_en=Composer,arranged_for=musicbox-30,reading_ja=かすたむ,category=classical-folk,time_signature=3/4\nC-1,C5,G9\n\n')});await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='カスタム'&&document.querySelector('#cancelImport').hidden);assert.equal(await page.locator('#subdivision').inputValue(),'7');const custom=await save();assert.equal(custom.stepMs,1234);assert.equal(custom.length,2);assert.deepEqual(custom.notes,[{step:0,midi:72}]);assert.equal(custom.metadata.extra,'保つ');assert.deepEqual(Object.keys(custom.metadata).sort(),['format','version','step_ms','title','extra'].sort(),'取り込んだサンプル用・削除済み項目もプレビュー・コピー・TXTから除外');await page.locator('#copyText').click();assert.deepEqual(parseText(await page.evaluate(()=>navigator.clipboard.readText())),parseText(await preview.inputValue()));assert(await page.locator('#errorMessage').isHidden());await page.selectOption('#instrument','piano-88');assert.equal(await page.locator('#noteStats').textContent(),'3音 · 2ステップ','出力・楽器変更で編集中の音を削除しない');assert.equal((await save()).notes.length,1);await page.selectOption('#instrument','musicbox-30');
  await page.selectOption('#language','en');await page.waitForFunction(()=>document.documentElement.lang==='en');assert.equal(await page.locator('#subdivision option:checked').textContent(),'7 steps per quarter');await page.selectOption('#language','ja');await page.waitForFunction(()=>document.documentElement.lang==='ja');await page.locator('#reset').click();
  const piano=JSON.parse(await readFile('dist/audio/soundsets.json','utf8')).find(item=>item.id==='vsco-piano');
  const pianoDurations=await page.evaluate(async bank=>{const context=new AudioContext({sampleRate:44100}),durations={};try{for(const [note,file] of Object.entries(bank.files)){const response=await fetch(bank.base+encodeURIComponent(file)+'?v='+bank.revision);if(!response.ok)throw new Error(note+'を読み込めません');const buffer=await context.decodeAudioData(await response.arrayBuffer());if(buffer.numberOfChannels!==2||buffer.sampleRate!==44100||buffer.duration<=0)throw new Error(note+'の音声が不正です');durations[note]=buffer.duration;}}finally{await context.close();}return durations;},piano);assert.equal(Object.keys(pianoDurations).length,88,'全88鍵をブラウザでデコードできる');
  await page.selectOption('#instrument','piano-88');await page.locator('#fileInput').setInputFiles({name:'piano-check.txt',mimeType:'text/plain',buffer:Buffer.from('format=stepscore,version=1,step_ms=250,title=ピアノ確認\nA0\nC4,E4,G4\nA4\nC8\nC#5\n\n\n\n')});await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='ピアノ確認'&&document.querySelector('#cancelImport').hidden);const pianoText=await preview.inputValue();await page.locator('#play').click();await page.waitForSelector('.step-label.playing');assert(await page.locator('#errorMessage').isHidden());await page.locator('#play').click();
  for(const [button,extension] of [['exportOgg','ogg'],['exportMp3','mp3']]){await page.locator('#save').click();const pending=page.waitForEvent('download');await page.locator('#'+button).click();const download=await pending;await download.saveAs('.sites-runtime/piano-check.'+extension);assert((await readFile(await download.path())).length>10000);assert.equal(await preview.inputValue(),pianoText,'録音ピアノの音声書き出しで楽譜を変更しない');assert(await page.locator('#errorMessage').isHidden());}
  await page.selectOption('#instrument','musicbox-30');await page.locator('#reset').click();
  // 基本名がないTXTは他言語の表示名を基本名にし、改名時は未知の言語名も取り除く。
  await page.locator('#fileInput').setInputFiles({name:'titles.txt',mimeType:'text/plain',buffer:Buffer.from(serialize([],1,125,{title_fr:'Nom français'}))});await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='Nom français'&&document.querySelector('#cancelImport').hidden);assert.equal(parseText(await preview.inputValue()).metadata.title,'Nom français');await page.locator('#scoreTitle').fill('自分の曲');await page.locator('#scoreTitle').press('Enter');assert.deepEqual(Object.keys(parseText(await preview.inputValue()).metadata).sort(),['format','version','step_ms','title'].sort());await page.selectOption('#language','en');await page.waitForFunction(()=>document.documentElement.lang==='en');assert.equal(await page.locator('#scoreTitle').inputValue(),'自分の曲');await page.selectOption('#language','ja');await page.waitForFunction(()=>document.documentElement.lang==='ja');await page.keyboard.press('Control+z');assert.equal(parseText(await preview.inputValue()).metadata.title_fr,'Nom français');await page.locator('#reset').click();
  await page.locator('#scoreTitle').fill('新しく付けた名前');await page.locator('#scoreTitle').press('Enter');assert.equal(parseText(await preview.inputValue()).metadata.title,'新しく付けた名前');await page.selectOption('#language','en');await page.waitForFunction(()=>document.documentElement.lang==='en');assert.equal(await page.locator('#scoreTitle').inputValue(),'新しく付けた名前');await page.selectOption('#language','ja');await page.waitForFunction(()=>document.documentElement.lang==='ja');await page.locator('#reset').click();
  // 表示BPMから間隔を再計算すると1234msが1224msになるケース。移調・単位変更は元のmsを使う。
  await page.locator('#fileInput').setInputFiles({name:'tempo.txt',mimeType:'text/plain',buffer:Buffer.from('format=stepscore,version=1,step_ms=1234,steps_per_quarter=7\nC5\n\n')});await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='tempo'&&document.querySelector('#cancelImport').hidden);assert.equal(await tempo.inputValue(),'7');assert.equal(parseText(await page.locator('#txtPreview').inputValue()).stepMs,1234);
  await page.locator('#transpose').fill('1');await page.waitForFunction(()=>document.querySelector('#txtPreview').value.includes('C#5')&&document.querySelector('#cancelImport').hidden);assert.equal(parseText(await page.locator('#txtPreview').inputValue()).stepMs,1234,'移調で丸めたBPMを再適用しない');
  await page.selectOption('#subdivision','4');await page.waitForFunction(()=>document.querySelector('#cancelImport').hidden);assert.equal(parseText(await page.locator('#txtPreview').inputValue()).stepMs,2160,'ステップ単位は元のmsから換算');assert.equal(await tempo.inputValue(),'7');await page.locator('#reset').click();
  const rangeNotes=[{step:0,midi:72},{step:4,midi:66},{step:5,midi:127},{step:8,midi:76},{step:12,midi:79},{step:20,midi:84}];
  await page.locator('#fileInput').setInputFiles({name:'range.txt',mimeType:'text/plain',buffer:Buffer.from(serialize(rangeNotes,24,125,{steps_per_quarter:'4',time_signature:'4/4',extra:'保つ'}))});await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='range'&&document.querySelector('#cancelImport').hidden);
  const header=step=>page.locator(`.step-label[data-step="${step}"]`),visibleScore=()=>page.locator('#txtPreview').inputValue().then(parseText),dragHeaders=async(first,last)=>{await header(first).scrollIntoViewIfNeeded();const a=await header(first).boundingBox(),b=await header(last).boundingBox();await page.mouse.move(a.x+4,a.y+a.height/2);await page.mouse.down();await page.mouse.move(b.x+b.width-4,b.y+b.height/2,{steps:12});await page.mouse.up();};
  await header(7).click();assert.equal(await page.locator('.step-label.selected').getAttribute('data-step'),'7','クリックしたマスを再生開始位置にする');assert(await page.locator('#deleteRange').isDisabled());assert.equal(await page.locator('.step-label.time-selected').count(),0,'クリックだけでは範囲を選択しない');await page.locator('#play').click();await page.waitForFunction(()=>Number(document.querySelector('.step-label.playing')?.dataset.step)>=7);await page.locator('#play').click();assert.equal(await page.locator('.step-label.selected').getAttribute('data-step'),'0','停止は以前と同じく先頭に戻る');
  await dragHeaders(3,13);await page.locator('#deleteRange').click();let cut=await visibleScore();assert.equal(cut.length,24,'通常の削除はマス目を残す');assert.equal(cut.stepMs,125);assert.equal(cut.metadata.extra,'保つ');assert.deepEqual(cut.notes,[{step:0,midi:72},{step:20,midi:84}],'後続音の位置を保つ');assert.equal(await page.locator('#noteStats').textContent(),'2音 · 24ステップ','非対応・非表示の音も消す');assert(await page.locator('#midiPanel').isHidden());assert(await page.locator('#unsupportedPanel').isHidden());await page.keyboard.press('Control+z');assert.equal(await page.locator('#noteStats').textContent(),'6音 · 24ステップ');assert(!(await page.locator('#midiPanel').isHidden()));
  await dragHeaders(4,4);assert.equal(await page.locator('.step-label.time-selected').count(),1);assert.equal(await page.locator('.cell.time-selected').count(),41);await page.locator('#collapseRange').click();cut=await visibleScore();assert.equal(cut.length,23);assert.equal(cut.stepMs,125);assert.equal(cut.metadata.extra,'保つ');assert.deepEqual(cut.notes,[{step:0,midi:72},{step:7,midi:76},{step:11,midi:79},{step:19,midi:84}]);assert.equal(await page.locator('#noteStats').textContent(),'5音 · 23ステップ','削除は選択した1ステップだけ');assert(await page.locator('#midiPanel').isHidden());
  await page.keyboard.press('Control+z');assert.equal(await page.locator('#noteStats').textContent(),'6音 · 24ステップ');assert(!(await page.locator('#midiPanel').isHidden()));assert.equal(await page.locator('#exportWarning').textContent(),'非対応：2音（再生・出力から除外）','取り消しで非対応音の数も復元');
  for(const key of ['Delete','Backspace']){
    await dragHeaders(3,13);await page.keyboard.press(key);cut=await visibleScore();assert.equal(cut.length,24,`${key}では時間を詰めない`);assert.deepEqual(cut.notes,[{step:0,midi:72},{step:20,midi:84}]);assert.equal(cut.stepMs,125);assert.equal(cut.metadata.extra,'保つ');assert(await page.locator('#deleteRange').isDisabled());assert(await page.locator('#collapseRange').isDisabled());assert(await page.locator('#midiPanel').isHidden());await page.keyboard.press('Control+z');assert.equal(await page.locator('#noteStats').textContent(),'6音 · 24ステップ');assert(!(await page.locator('#midiPanel').isHidden()));
  }
  await dragHeaders(3,13);const beforeTyping=await visibleScore(),title=page.locator('#scoreTitle'),originalTitle=await title.inputValue();await title.focus();await title.press('End');await title.press('Backspace');assert.equal(await title.inputValue(),originalTitle.slice(0,-1),'入力欄のBackspaceは文字を消す');assert.deepEqual(await visibleScore(),{...beforeTyping,metadata:{...beforeTyping.metadata,title:originalTitle.slice(0,-1)}},'入力欄では曲名だけ変更し、選択区間を削除しない');assert.equal(await page.locator('.step-label.time-selected').count(),11);await title.fill(originalTitle);await header(3).focus();
  for(const key of ['Control+Delete','Alt+Delete']){await page.keyboard.press(key);assert.deepEqual(await visibleScore(),beforeTyping);assert.equal(await page.locator('.step-label.time-selected').count(),11);}
  await header(3).dispatchEvent('keydown',{key:'Delete',isComposing:true});assert.deepEqual(await visibleScore(),beforeTyping,'IME入力中は区間を削除しない');await page.keyboard.press('Escape');
  await dragHeaders(13,3);assert.equal(await page.locator('.step-label.time-selected').first().getAttribute('data-step'),'3');assert.equal(await page.locator('.step-label.time-selected').count(),11,'拍の途中から右から左へ選択');assert.equal(await page.locator('.step-label.selected').getAttribute('data-step'),'13','範囲の始点を広げても再生開始位置を動かさない');await page.keyboard.press('Shift+Backspace');cut=await visibleScore();assert.equal(cut.length,13);assert.deepEqual(cut.notes,[{step:0,midi:72},{step:9,midi:84}],'後続音と末尾休符を同じ幅だけ詰める');assert.equal(await page.locator('#noteStats').textContent(),'2音 · 13ステップ','非対応音と非表示のG9も区間ごと削除');await page.keyboard.press('Control+z');assert.equal(await page.locator('#noteStats').textContent(),'6音 · 24ステップ');
  await header(8).dblclick();assert.equal(await page.locator('.step-label.time-selected').count(),0,'ダブルクリックでも小節を選ばない');assert.equal(await page.locator('.step-label.selected').getAttribute('data-step'),'8');
  await header(0).click();await header(0).press('ArrowRight');assert.equal(await page.locator('.step-label.selected').getAttribute('data-step'),'1','矢印も1ステップずつ移動');await dragHeaders(5,9);await page.keyboard.press('Escape');assert(await page.locator('#deleteRange').isDisabled());assert.equal(await page.locator('.step-label.selected').getAttribute('data-step'),'5','範囲を解除してもクリックした開始位置は保つ');
  await dragHeaders(0,23);await page.locator('#deleteRange').click();cut=await visibleScore();assert.equal(cut.length,24);assert.equal(cut.notes.length,0,'全範囲の通常削除は休符として残す');await page.keyboard.press('Control+z');assert.equal(await page.locator('#noteStats').textContent(),'6音 · 24ステップ');
  await dragHeaders(0,23);await page.keyboard.press('Shift+Delete');cut=await visibleScore();assert.equal(cut.length,1);assert.equal(cut.notes.length,0,'全区間を詰めて削除すると空の1ステップを残す');await page.keyboard.press('Control+z');assert.equal(await page.locator('#noteStats').textContent(),'6音 · 24ステップ');
  const tripleNotes=[{step:0,midi:72},{step:2,midi:76},{step:14,midi:79},{step:21,midi:84}];await page.locator('#fileInput').setInputFiles({name:'triple.txt',mimeType:'text/plain',buffer:Buffer.from(serialize(tripleNotes,22,172,{steps_per_quarter:'4',time_signature:'3/4'}))});await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='triple'&&document.querySelector('#cancelImport').hidden);
  await dragHeaders(20,21);assert.equal(await page.locator('.step-label.time-selected').count(),2,'3拍子でもステップ単位');await page.locator('#collapseRange').click();cut=await visibleScore();assert.equal(cut.length,20);assert.equal(cut.stepMs,172);assert(!('time_signature' in cut.metadata));assert(await header(12).evaluate(element=>element.classList.contains('bar')),'編集中の3拍子の小節線は区間削除後も保つ');assert.deepEqual(cut.notes,tripleNotes.slice(0,3));await page.keyboard.press('Control+z');assert.deepEqual((await visibleScore()).notes,tripleNotes);
  const elise=parseText(await readFile('dist/samples/fur-elise-musicbox-30.txt','utf8'));await page.selectOption('#templateSelect','fur-elise-musicbox-30');await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='エリーゼのために');const eliseOutput=await visibleScore();assert.deepEqual([eliseOutput.notes,eliseOutput.length,eliseOutput.stepMs],[elise.notes,elise.length,elise.stepMs],'導入の音と再生間隔は変えない');await header(1).click();assert.equal(await page.locator('.step-label.selected').getAttribute('data-step'),'1','拍の途中のマスも開始位置にできる');await dragHeaders(1,4);assert.equal(await page.locator('.step-label.time-selected').first().getAttribute('data-step'),'1');assert.equal(await page.locator('.step-label.time-selected').count(),4,'3/8でも拍・小節に丸めない');
  await page.selectOption('#templateSelect','pachelbel-canon-musicbox-30');await page.waitForFunction(()=>document.querySelector('#scoreTitle').value==='カノン');await page.screenshot({path:'.sites-runtime/refactor-desktop.png',fullPage:true});
  await dragHeaders(3,31);await page.screenshot({path:'.sites-runtime/range-selection.png',fullPage:true});await page.evaluate(()=>{document.querySelector('#rollViewport').scrollLeft=600;});await page.waitForSelector('.step-label[data-step="50"]',{state:'attached'});assert(await page.locator('.step-label.time-selected').count()>0,'仮想描画で選択区間を保持');assert(await page.locator('#deleteRange').isEnabled());await page.evaluate(()=>{document.querySelector('#rollViewport').scrollLeft=0;});await page.waitForSelector('.step-label[data-step="0"]',{state:'attached'});assert.equal(await page.locator('.step-label.time-selected').count(),29);await page.keyboard.press('Escape');
  await page.setViewportSize({width:390,height:844});assert(await page.locator('#rollViewport').evaluate(element=>element.scrollHeight<=element.clientHeight),'モバイルでも鍵盤を縦スクロールしない');await page.locator('#txtPreviewPanel summary').click();assert(await preview.evaluate(element=>element.scrollWidth<=element.clientWidth),'モバイルでも長いヘッダーを折り返す');await page.screenshot({path:'.sites-runtime/refactor-mobile.png',fullPage:true});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'モバイルでページ全体が横にはみ出さない');
  const mobile=await browser.newPage({viewport:{width:390,height:844},hasTouch:true,isMobile:true,locale:'ja-JP'});mobile.on('pageerror',error=>errors.push(error.message));await mobile.goto(process.argv[2]??'http://127.0.0.1:4173');await mobile.waitForSelector('#instrument option',{state:'attached'});await mobile.locator('.step-label[data-step="4"]').tap();assert.equal(await mobile.locator('.step-label.selected').getAttribute('data-step'),'4');assert.equal(await mobile.locator('.step-label.time-selected').count(),0);assert(await mobile.locator('#deleteRange').isDisabled());
  await mobile.locator('#fileInput').setInputFiles({name:'touch.txt',mimeType:'text/plain',buffer:Buffer.from(serialize([{step:0,midi:72},{step:10,midi:76}],32,125))});await mobile.waitForFunction(()=>document.querySelector('#scoreTitle').value==='touch'&&document.querySelector('#cancelImport').hidden);
  const touchSession=await mobile.context().newCDPSession(mobile),touchA=await mobile.locator('.step-label[data-step="0"]').boundingBox(),touchB=await mobile.locator('.step-label[data-step="8"]').boundingBox();await touchSession.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:touchA.x+15,y:touchA.y+14}]});for(let i=1;i<=8;i++)await touchSession.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:touchA.x+15+(touchB.x-touchA.x)*i/8,y:touchA.y+14}]});await touchSession.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await mobile.locator('.step-label.time-selected').count(),9,'タッチでもステップ単位で選ぶ');
  // Chromiumの合成タッチはドラッグ直後のタップを無視するため、ジェスチャーの終了を待つ。
  await new Promise(resolve=>setTimeout(resolve,1000));await mobile.locator('#deleteRange').tap();await mobile.waitForFunction(()=>document.querySelector('#noteStats').textContent==='1音 · 32ステップ');const touchScore=parseText(await mobile.locator('#txtPreview').inputValue());assert.equal(touchScore.length,32);assert.deepEqual(touchScore.notes,[{step:10,midi:76}],'タップで音だけ消し、後続音の位置を保つ');await mobile.close();
  assert(!errors.length,errors.join('\n'));console.log('ブラウザ確認成功：保存・再取り込み・言語・楽器・試聴・連続入力・移動・ステップ範囲削除・取り消し・Worker中止・失敗時の保持・仮想描画・モバイル');
}finally{await browser.close();}
